booking/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    url(r'^$',
        login_required(views.DetailView.as_view())),
    url(r'^(?P<pk>[0-9]+)/$',
        login_required(views.BookingDetailView.as_view()),
        name='detail'),
]

hotel/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^$', views.index),
]

hotelhammy/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^$', include('listing.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^hotel/', include('hotel.urls')),
    url(r'^listing/', include('listing.urls', namespace="listing")),
    url(r'^booking/', include('booking.urls', namespace='booking')),

    url(r'^admin/', include(admin.site.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

listing/urls.py
from django.conf.urls import url
from . import views
from django.contrib import admin

urlpatterns = [
    # e.g. /listing/
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^s/', views.SearchView.as_view(), name='search'),
    # e.g. /listing/1/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
]

booking/models.py
from django.db import models
from django.conf import settings
from django.contrib.postgres.fields import DateRangeField

from hotel.models import Room

# Create your models here.

class Booking(models.Model):
    made_by = models.ForeignKey(settings.AUTH_USER_MODEL)
    room = models.ForeignKey(Room)
    period = DateRangeField()

    def __str__(self):
        return '%s %s - %s' % (self.room, self.period.lower, self.period.upper)

hotel/models.py
from django.db import models

class Hotel(models.Model):
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Room(models.Model):
    hotel = models.ForeignKey(Hotel)
    beds = models.IntegerField(default=1)

    def featured_image(self):
        featured = self.photos.first()
        return featured.image if featured else ""

    def featured_image_url(self):
        featured = self.photos.first()
        return featured.image.url if featured else ""

    def __str__(self):
        return '%s %s beds' % (self.hotel, self.beds)

def upload_path(instance, filename):
    return '%s/%s' % (instance._meta.model_name, filename)

class Photo(models.Model):
    image = models.ImageField(upload_to=upload_path)

    class Meta:
        abstract = True

class HotelPhoto(Photo):
    hotel = models.ForeignKey(Hotel, related_name="photos")

class RoomPhoto(Photo):
    room = models.ForeignKey(Room, related_name="photos")

listing/models.py
from django.db import models
from django.contrib.postgres.fields import DateRangeField

from hotel.models import Room

class Availability(models.Model):
    room = models.ForeignKey(Room)
    period = DateRangeField()

    def __str__(self):
        return '%s %s - %s' % (self.room, self.period.lower, self.period.upper)

    class Meta:
        verbose_name_plural = 'availabilities'

booking/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.views import generic

from psycopg2.extras import DateRange

from booking.models import Booking
from hotel.models import Room


class BookingDetailView(generic.DetailView):
    model = Booking
    template_name = 'booking/detail.html'


class DetailView(generic.DetailView):
    def post(self, request):
        room_id = request.POST.get('room')
        start = request.POST.get('checkIn')
        end = request.POST.get('checkOut')
        if not start or not end:
            return HttpResponse()
        room = Room.objects.get(pk=room_id)
        booking = Booking.objects.create(
            made_by=request.user,
            room=room,
            period=DateRange(start, end))
        return redirect('/booking/%s/' % booking.pk)

hotel/views.py
from django.shortcuts import render
from django.http import HttpResponse

from .models import Hotel

def index(request):
    context = {'hotels': Hotel.objects.all()}
    return render(request, 'hotel/index.html', context)

listing/views.py
import logging

from datetime import date

from dateutil import parser

from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.views import generic
from psycopg2.extras import DateRange

from .models import Availability

LOG = logging.getLogger(__name__)


class IndexView(generic.ListView):
    template_name = 'listing/index.html'
    context_object_name = 'listings'

    def get_queryset(self):
        return Availability.objects.all()

class SearchView(generic.View):
    def get(self, request):
        form_data = request.GET
        check_in = form_data.get('checkIn')
        check_out = form_data.get('checkOut')

        log_search(check_in, check_out)

        in_date = parse_date(check_in)
        out_date = parse_date(check_out)
        date_range = DateRange(in_date, out_date)

        available = Availability.objects.filter(period__contains=date_range)
        available = available.select_related('room')

        log_results(available)

        context = {
            'form': form_data,
            'listings': available,
        }
        template_name = "listing/search.html"
        return render(request, template_name, context)

class DetailView(generic.DetailView):
    model = Availability
    template_name = 'listing/detail.html'

def parse_date(a_date):
    return parser.parse(a_date, default=date.today())

def log_search(check_in, check_out):
    LOG.info('event=search, check_in=%s, check_out=%s', check_in, check_out)

def log_results(results):
    LOG.info('event=search_result, result=%s', results)

booking/templates/booking/detail.html
{% extends "base.html" %}
{% load imagekit %}
{% block content %}
{% include "listing/booking_modal.html" %}
<img src="{{ booking.room.featured_image.url }}" alt="" class="cover"/>
<div class="container">
  <div class="row">
    <div class="hotel-desc">
      <div class="col-sm-8 col-xs-12">
        <h2>{{ booking.room.hotel }} <span class="label label-danger">Hot</span></h2>
        <h3>{{ booking.room.beds }}-bed</h3>
        {% if booking.period.upper %}
        <div>{{ booking.period.lower }}</div>
        <div>{{ booking.period.upper }}</div>
        {% else %}
        <div>Available from {{ booking.period.lower }}</div>
        {% endif %}
      </div>
      <div class="col-sm-4 col-xs-12 hotel-desc-right">
        <label for="book"></label>
        <button type="button" name="book" id="book" value="You've booked." class="btn btn-lg btn-block btn-success" disabled="disabled">
          You've booked this room.
        </button>
        <div class="price">
          $100
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

hotel/templates/hotel/base.html
<html>
  <head>
  <head>
  <body>
  {% block content %}{% endblock content %}
  </body>
</html>

hotel/templates/hotel/index.html
{% extends "hotel/base.html" %}
{% block content %}
<ul>
  {% for hotel in hotels %}
  <li>
      <div>{{ hotel.name }}</div>
      <div>{{ hotel.room_set.count }} rooms</div>
      <div>{{ hotel.address }}</div>
  </li>
  {% endfor %}
</ul>
{% endblock content %}

listing/templates/listing/booking_modal.html
<form class="form-inline" method="POST" action="/booking/">
{% csrf_token %}
<input type="hidden" name="room" value="{{ availability.room.pk }}" />
<div class="modal fade" id="booking-modal" tabindex="-1" role="dialog" aria-labelledby="bookinModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        Choose your dates of stay
      </div>
      <div class="modal-body">
        <div class="card-wrapper">
        </div>
        <div>
          <div class="form-group">
            <label class="sr-only" for="checkIn">Check In</label>
            <input type="text" class="form-control datepicker" id="checkIn" placeholder="Check In" value="{{ form.checkIn }}" data-provide="datepicker" name="checkIn" required>
          </div>
          <div class="form-group">
            <label class="sr-only" for="checkOut">Check Out</label>
            <input type="text" class="form-control datepicker" id="checkOut" placeholder="Check Out" value="{{ form.checkOut }}" data-provide="datepicker" name="checkOut" required>
          </div>

              <!--
          <div id="creditcard">
            <div class="form-group">
              <input class="form-control" name="number" placeholder="Card number">
            </div>
            <div class="form-group">
              <input class="form-control" name="name" placeholder="Name on card">
            </div>
            <div class="form-group">
              <input class="form-control" name="expiry" placeholder="Expiry">
            </div>
            <div class="form-group">
              <input class="form-control" name="cvc" placeholder="CVC">
            </div>
          </div>
          -->
            </div>
          </div>
      <div class="modal-footer">
        <input type="submit" value="Book" class="btn btn-success"/>
        <button type="text" value="" class="btn btn-link" data-toggle="modal" data-target="#booking-modal">Cancel</button>
      </div>
    </div>
  </div>
</div>
</form>

<script type="text/javascript" charset="utf-8">
// $('#creditcard').card({
  // a selector or DOM element for the container
  // where you want the card to appear
  // container: '.card-wrapper', // *required*
  // all of the other options from above
// });
</script>

listing/templates/listing/detail.html
{% extends "base.html" %}
{% load imagekit %}
{% block content %}
{% include "listing/booking_modal.html" %}
<img src="{{ availability.room.featured_image.url }}" alt="" class="cover"/>
<div class="container">
  <div class="row">
    <div class="hotel-desc">
      <div class="col-sm-8 col-xs-12">
        <h2>{{ availability.room.hotel }} <span class="label label-danger">Hot</span></h2>
        <h3>{{ availability.room.beds }}-bed</h3>
        {% if availability.period.upper %}
        <div>{{ availability.period.lower }}</div>
        <div>{{ availability.period.upper }}</div>
        {% else %}
        <div>Available from {{ availability.period.lower }}</div>
        {% endif %}
      </div>
      <div class="col-sm-4 col-xs-12 hotel-desc-right">
        <label for="book"></label>
        <button type="button" name="book" id="book" value="Book now!" class="btn btn-lg btn-block btn-primary" data-toggle="modal" data-target="#booking-modal">
          Book now!
        </button>
        <div class="price">
          $100
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

listing/templates/listing/exclusive_list.html
<h2 class="text-center">
    Exclusive Deals
</h2>
{% for listing in listings %}
{% if forloop.counter|divisibleby:"2" %}
<div class="row">
{% endif %}
{% include "listing/listing_single.html" %}
{% if forloop.counter|divisibleby:"2" %}
</div>
{% endif %}
{% endfor %}

listing/templates/listing/index.html
{% extends "base.html" %}

{% block jumbo %}
<div class="jumbotron">
  <div class="container">
    <div class="row text-center">
      <h1>Staycations</h1>
      <h2>at your fingertips</h2>
    </div>
    {% block search %}
    <div class="row search">
      <div class="col-md-8 col-md-offset-2 text-center">
        {% include "listing/search_form.html" %}
      </div>
    </div>
    {% endblock search %}
  </div>
</div>
{% endblock jumbo %}

{% block content %}
<div class="container">
  {% include "listing/exclusive_list.html" %}
  {% include "listing/listing_list.html" %}
</div>
{% endblock content %}

listing/templates/listing/listing_single.html
{% load imagekit %}
<div class="col-md-6 col-sm-12">
    <div class="thumbnail">
        <a href="{% url 'listing:detail' listing.id %}">
            {% thumbnail '750x500' listing.room.featured_image -- class="listing-image" %}
        </a>
        <div class="price">
            $100
        </div>
        <div class="caption">
            <h4>{{ listing.room.hotel }}</h4>
            <h5>{{ listing.room.beds }}-bed</h5>
            {% if listing.period.upper %}
            <div>{{ listing.period.lower }}</div>
            <div>{{ listing.period.upper }}</div>
            {% else %}
            <div>Available from {{ listing.period.lower }}</div>
            {% endif %}
        </div>
    </div>
</div>

listing/templates/listing/search.html
{% extends "base.html" %}

{% block jumbo %}
<div class="jumbotron">
    <div class="container">
        {% block search %}
        <div class="row">
            <div class="col-md-8 col-md-offset-2 text-center">
                {% include "listing/search_form.html" %}
            </div>
        </div>
    </div>
</div>
{% endblock search %}
{% endblock jumbo %}

{% block content %}
<style>
.responsive-img {
    height: 100%;
}
</style>
<div class="container">
    {% include "listing/listing_list.html" %}
</div>
{% endblock content %}

listing/templates/listing/search_form.html
<form id="search-form" class="form-inline" method="get" action="/listing/s/">
    <div class="form-group">
        <label class="sr-only" for="where">Where</label>
        <input type="text" class="form-control awesomplete" data-list="Manhattan, Brooklyn, Queens, Harlem" id="where" name="where" placeholder="Where" value="{{ form.where }}">
    </div>
    <div class="form-group">
        <label class="sr-only" for="checkIn">Check In</label>
        <input type="text" class="form-control datepicker" id="checkIn" name="checkIn" placeholder="Check In" value="{{ form.checkIn }}" data-provide="datepicker">
    </div>
    <div class="form-group">
        <label class="sr-only" for="checkOut">Check Out</label>
        <input type="text" class="form-control datepicker" id="checkOut" name="checkOut" placeholder="Check Out" value="{{ form.checkOut }}" data-provide="datepicker">
    </div>
    <button type="submit" class="btn btn-default">Find a place!</button>
</form>

templates/accounts_modal.html
<form class="signup" id="signup_form" method="post" action="{% url 'account_signup' %}">
  {% csrf_token %}
  <input type="hidden" name="next" value="/" />
  <div class="modal fade" id="accounts-modal" tabindex="-1" role="dialog" aria-labelledby="accountsModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body">
          {% comment %}
          {% load socialaccount %}
          {% providers_media_js %}
          <a class="btn btn-default btn-lg btn-block" href="{% provider_login_url "facebook" method="js_sdk" %}">Facebook Connect</a>
          <p class="accounts-separator text-center">or</p>
          {% endcomment %}
          <p></p>
          <div class="form-group">
            <div class="input-group input-group-lg">
              <input type="email" class="form-control input-lg" id="email" placeholder="Enter email" name="email">
              <span class="input-group-addon">
                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
              </span>
            </div>
          </div>
          <div class="form-group">
            <div class="input-group input-group-lg">
              <input type="password" class="form-control input-lg" id="password1" placeholder="Password" name="password1">
              <span class="input-group-addon">
                <span class="glyphicon glyphicon-lock" aria-hidden="true"></span>
              </span>
            </div>
          </div>
          <div class="form-group">
            <div class="input-group input-group-lg">
              <input type="password" class="form-control input-lg" id="password2" placeholder="Repeat password" name="password2">
              <span class="input-group-addon">
                <span class="glyphicon glyphicon-lock" aria-hidden="true"></span>
              </span>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <input type="submit" value="Sign Up" class="btn btn-success"/>
          <button type="text" value="" class="btn btn-link">Forgot?</button>
        </div>
      </div>
    </div>
  </div>
</form>

templates/base.html
{% load staticfiles %}
<!doctype html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>HotelHare</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="apple-touch-icon" href="apple-touch-icon.png">
        <link type="text/css" rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
        <link type="text/css" rel="stylesheet" href="{% static "css/bootstrap-datepicker.css" %}">
        <link type="text/css" rel="stylesheet" href="{% static "css/main.css" %}">
        <link type="text/css" rel="stylesheet" href="{% static "css/awesomplete.css" %}">

    </head>
    <body>
        <script src="{% static "js/jquery.js" %}"></script>
        <script src="{% static "js/jquery.card.js" %}"></script>
        <script src="{% static "js/bootstrap.js" %}"></script>
        <script src="{% static "js/bootstrap-datepicker.js" %}"></script>
        <script src="{% static "js/awesomplete.js" %}"></script>
        <script src="{% static "js/main.js" %}"></script>


    {% include "nav.html" %}

    {% block jumbo %}
    {% endblock jumbo %}

    {% block content %}
    {% endblock content %}
    <footer id="" class="text-center">
    &copy; 2015 HotelHare (school project)
    </footer>
    {% include "accounts_modal.html" %}
    {% include "login_modal.html" %}
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="{% static 'js/vendor/jquery-1.11.2.min.js' %}"><\/script>')</script>

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <!-- <script> -->
        <!--     (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]= -->
        <!--     function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date; -->
        <!--     e=o.createElement(i);r=o.getElementsByTagName(i)[0]; -->
        <!--     e.src='//www.google-analytics.com/analytics.js'; -->
        <!--     r.parentNode.insertBefore(e,r)}(window,document,'script','ga')); -->
        <!--     ga('create','UA-XXXXX-X','auto');ga('send','pageview'); -->
        <!-- </script> -->
    </body>
</html>

templates/login_modal.html
<form class="login" id="login_form" method="POST" action="{% url 'account_login' %}">
  {% csrf_token %}
  <input type="hidden" name="next" value="/" />
  <div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body">
          {% comment %}
          {% load socialaccount %}
          {% providers_media_js %}
          <a class="btn btn-default btn-lg btn-block" href="{% provider_login_url "facebook" method="js_sdk" %}">Facebook Connect</a>
          {% endcomment %}
          <p></p>
          <form>
            <div class="form-group">
              <div class="input-group input-group-lg">
                <input type="email" class="form-control input-lg" id="email" placeholder="Enter email">
                <span class="input-group-addon">
                  <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                </span>
              </div>
            </div>
            <div class="form-group">
              <div class="input-group input-group-lg">
                <input type="password" class="form-control input-lg" id="password" placeholder="Password">
                <span class="input-group-addon">
                  <span class="glyphicon glyphicon-lock" aria-hidden="true"></span>
                </span>
              </div>
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <input type="submit" value="Login" class="btn btn-success"/>
          <button type="text" value="" class="btn btn-link">Forgot?</button>
        </div>
      </div>
    </div>
  </div>
</form>

templates/nav.html
<nav class="navbar" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand logo" href="/" alt="HotelHare logo"></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <form class="navbar-form navbar-right" role="form" method="post" action="{% url 'account_logout' %}">
        <div class="form-group">
          {% if request.user.is_authenticated %}
          <a>
            <span>{{ request.user.email }}</span>
          </a>
          {% else %}
          <button type="button" class="btn btn-link" data-toggle="modal" data-target="#accounts-modal">Sign Up</button>
          {% endif %}
        </div>
        <div class="form-group">
          {% if request.user.is_authenticated %}
            {% csrf_token %}
            <button type="submit" class="btn btn-link">Log Out</button>
          </form>
          {% else %}
          <button type="button" class="btn btn-link" data-toggle="modal" data-target="#login-modal">Log In</button>
          {% endif %}
        </div>
      </form>
    </div><!--/.navbar-collapse -->
  </div>
</nav>